### ISSUE TITLE
Unable to update an alias

### ISSUE THREAD

**Issue by minerkid** [hyle-team/zano#160] opened 2020-03-20 14:40 UTC
Comment section when attempting to transfer an alias is grayed out and not responsive.

User is still able to transfer alias but without comments

**Comment by cryptozoidberg** [comment] 2020-03-20 14:42
@zetov  please take a look into it

**Comment by sowle** [comment] 2020-03-28 21:04
fixed in 324673c1d33a41f0495827b2bbdcdc2f9c6be740

**Comment by sowle** [comment] 2020-04-01 08:28
Artemy: Now when transferring an alias, a user can change the comment, but it doesn't change in the blockchain, and hence, doesn't change when transferring the alias.

**Comment by sowle** [comment] 2020-06-05 12:02
The bug exists in 2cf31bca107a0cb019bb9c1af24dac7f287d5d92 and the problem is in the JS code. Back-end simply is not receiving correct alias update info.

Test case: A user should be able to rename and alias and (optionally) change the comment to it.

**Comment by sowle** [comment] 2020-06-26 11:03
Renaming an alias is an unsupported blockchain operation atm.
An alias can be 1) registered and 2) updated (i.e. change the address and/or text comment).
Renaming an alias is effectively registering a new one with discarding the old one at the same time.
Discarding an alias is unsupported.
We need to change the interface according to alias registration nature.

**Comment by cryptozoidberg** [comment] 2020-08-18 20:43
@sowle  i believe this is done already?

**Comment by sowle** [comment] 2020-08-19 15:01
@cryptozoidberg it's done in terms of GUI issues: now we only afford to change alias comment and it's working okay.
But we do not provide a way to change alias's bind-address, which is technically possible.

**Comment by cryptozoidberg** [comment] 2020-08-19 16:35
Need to add field Address and checkbox related to this field "Transfer alias", if this checkbox checked then edit box with address text becomes editable, and user can specify address where he want to transfer this alias. If checkbox unchecked then field is not editale, and text inside contains current alias address. 
![image](https://user-images.githubusercontent.com/7261328/90663847-75cc4500-e24a-11ea-9335-425678638f59.png)

**Closed** 2020-09-02 18:02 UTC
Labels: GUI, bug
